dependencies:
  - 'smartcontractkit/chainlink-brownie-contracts@0.4.1'
  - 'OpenZeppelin/openzeppelin-contracts@4.6.0'
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'

networks:
  default: development
  development:
    gas_lane: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    subscription_id: "1"
  rinkeby:
    chainlink_aggregator: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    gas_lane: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    subscription_id: ${VRF_SUB_ID}
    from_key: ${RINKEBY_PRIVATE_KEY}

wallets:
  from_key: ${RINKEBY_PRIVATE_KEY}
dotenv: .env